Requirement already satisfied: python-dateutil in c:\users\hp\anaconda3\lib\site-packages (2.1)
Requirement already satisfied: six in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil) (1.16.0)
